set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86-64)
set(CMAKE_CROSSCOMPILING TRUE)

set(triple "arm")
set(CMAKE_C_COMPILER clang)
#set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER clang++)
#set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_ASM_NASM_COMPILER nasm)

#set(CMAKE_CXX_FLAGS "-march=arm" CACHE STRING "" FORCE)
